/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BookingInquiry = IDL.Record({
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'checkInDate' : IDL.Text,
  'email' : IDL.Text,
  'numGuests' : IDL.Nat,
  'timestamp' : Time,
  'checkOutDate' : IDL.Text,
  'roomPreference' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBookingInquiries' : IDL.Func([], [IDL.Vec(BookingInquiry)], ['query']),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'submitBookingInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BookingInquiry = IDL.Record({
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'checkInDate' : IDL.Text,
    'email' : IDL.Text,
    'numGuests' : IDL.Nat,
    'timestamp' : Time,
    'checkOutDate' : IDL.Text,
    'roomPreference' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBookingInquiries' : IDL.Func(
        [],
        [IDL.Vec(BookingInquiry)],
        ['query'],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'submitBookingInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };